# -*- coding: utf-8 -*-
"""L5_DFNN_for_Classification_Complete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFe27QpLvuSD9kCUOveTvtFsxnEhKoyL
"""

#Import required Python libraries (numpy, pandas, matplotlib, sklearn).
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.datasets import fetch_covtype
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Load the Covertype dataset (581,012 samples, 54 features, 7 classes).
covtype = fetch_covtype()

X = covtype.data
y = covtype.target

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nFirst 20 target values:")
print(y[:20])

#Understand the problem: Multi-class classification of forest cover types.
print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])
print("Number of classes:", len(np.unique(y)))

print("\nUnique classes:")
print(np.unique(y))

unique_classes, class_counts = np.unique(y, return_counts=True)

print("Class Distribution:")
for cls, count in zip(unique_classes, class_counts):
    print(f"Class {cls}: {count} samples")

#Analyze class distribution: Calculate imbalance ratio between most/least frequent classes
max_count = np.max(class_counts)
min_count = np.min(class_counts)

imbalance_ratio = max_count / min_count

print("Imbalance Ratio:", imbalance_ratio)

#Explore data: Visualize class distribution, identify class imbalance.
plt.figure(figsize=(8, 5))

plt.bar(unique_classes, class_counts)

plt.xlabel("Forest Cover Type")
plt.ylabel("Number of Samples")
plt.title("Class Distribution")

plt.xticks(unique_classes)

plt.show()

#Convert target classes from 1-7 to 0-6 for zero-indexing.
y = y - 1

print("Classes after conversion:")
print(np.unique(y))

#One-hot encode target: Convert to binary matrix [N Ö 7].
num_classes = 7

Y = np.eye(num_classes)[y]

print("One-hot encoded target shape:")
print(Y.shape)

print("\nExample:")
print("Original class:", y[0])
print("One-hot:", Y[0])

#Partition dataset into training (80%), validation (10%), and testing (10%) sets.
X_train, X_temp, Y_train, Y_temp, y_train, y_temp = train_test_split(
    X,
    Y,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

X_val, X_test, Y_val, Y_test, y_val, y_test = train_test_split(
    X_temp,
    Y_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

#Ensure stratified splits to maintain class proportions in all sets.
print("Data split:")
print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

#Standardize features using StandardScaler (zero mean, unit variance).
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_val = scaler.transform(X_val)

X_test = scaler.transform(X_test)

print("Training mean approximately:",
      np.mean(X_train))

print("Training standard deviation approximately:",
      np.std(X_train))

#Calculate class weights: wc = N/K×nc to handle imbalance.
N = len(y_train)
K = num_classes

class_weights = {}

for c in range(K):

    nc = np.sum(y_train == c)

    class_weights[c] = N / (K * nc)

print("Class Weights:")

for c in range(K):
    print(
        f"Class {c}: "
        f"{class_weights[c]:.4f}"
    )

class_weight_array = np.array(
    [class_weights[c] for c in range(K)]
)

print("\nClass weight array:")
print(class_weight_array)

#Define network architecture: 4 layers [54, 64, 32, 16, 7].
layer_sizes = [54, 64, 32, 16, 7]

print("Network Architecture:")
print(layer_sizes)

#Initialize parameters using He initialization for ReLU: W(l) ∼ N (0,root(2/nl−1)).
def initialize_parameters(layer_sizes):

    parameters = {}

    for l in range(1, len(layer_sizes)):

        n_previous = layer_sizes[l - 1]
        n_current = layer_sizes[l]

        # He initialization
        parameters[f"W{l}"] = (
            np.random.randn(n_previous, n_current)
            * np.sqrt(2 / n_previous)
        )

        parameters[f"b{l}"] = np.zeros((1, n_current))

    return parameters


parameters = initialize_parameters(layer_sizes)


print("Parameter shapes:")

for key in parameters:
    print(key, parameters[key].shape)

total_parameters = 0

for l in range(1, len(layer_sizes)):

    total_parameters += (
        layer_sizes[l - 1] * layer_sizes[l]
    )

    total_parameters += layer_sizes[l]

print("Total trainable parameters:",
      total_parameters)

# Implement forward propagation with ReLU for hidden layers and softmax for output.
def relu(Z):
    return np.maximum(0, Z)

def relu_derivative(Z):
    return (Z > 0).astype(float)

def softmax(Z):
    # Subtract max for numerical stability
    Z_shifted = Z - np.max(
        Z,
        axis=1,
        keepdims=True
    )
    exp_Z = np.exp(Z_shifted)
    probabilities = (
        exp_Z /
        np.sum(exp_Z, axis=1, keepdims=True)
    )
    return probabilities

def forward_propagation(X, parameters):

    W1 = parameters["W1"]
    b1 = parameters["b1"]

    W2 = parameters["W2"]
    b2 = parameters["b2"]

    W3 = parameters["W3"]
    b3 = parameters["b3"]

    W4 = parameters["W4"]
    b4 = parameters["b4"]

    # Layer 1
    Z1 = X @ W1 + b1
    A1 = relu(Z1)

    # Layer 2
    Z2 = A1 @ W2 + b2
    A2 = relu(Z2)

    # Layer 3
    Z3 = A2 @ W3 + b3
    A3 = relu(Z3)

    # Output layer
    Z4 = A3 @ W4 + b4

    # Softmax
    Y_hat = softmax(Z4)

    cache = {
        "X": X,
        "Z1": Z1,
        "A1": A1,
        "Z2": Z2,
        "A2": A2,
        "Z3": Z3,
        "A3": A3,
        "Z4": Z4,
        "Y_hat": Y_hat
    }

    return Y_hat, cache

# Compute weighted categorical cross-entropy loss.
def compute_loss(Y, Y_hat, class_weight_array):

    # Find the class of each sample
    true_classes = np.argmax(Y, axis=1)

    # Weight corresponding to true class
    sample_weights = class_weight_array[true_classes]

    # Numerical stability
    epsilon = 1e-15

    Y_hat_clipped = np.clip(
        Y_hat,
        epsilon,
        1 - epsilon
    )

    # Categorical cross entropy
    cross_entropy = -np.sum(
        Y * np.log(Y_hat_clipped),
        axis=1
    )

    # Apply class weights
    weighted_loss = (
        sample_weights * cross_entropy
    )

    return np.mean(weighted_loss)

# Implement backpropagation with class weights applied to gradients.
def backward_propagation(
    Y,
    Y_hat,
    cache,
    parameters,
    class_weight_array
):

    X = cache["X"]

    Z1 = cache["Z1"]
    A1 = cache["A1"]

    Z2 = cache["Z2"]
    A2 = cache["A2"]

    Z3 = cache["Z3"]
    A3 = cache["A3"]

    W1 = parameters["W1"]
    W2 = parameters["W2"]
    W3 = parameters["W3"]
    W4 = parameters["W4"]

    B = X.shape[0]

    true_classes = np.argmax(Y, axis=1)

    sample_weights = class_weight_array[true_classes]

    sample_weights = sample_weights.reshape(-1, 1)

    dZ4 = (
        sample_weights *
        (Y_hat - Y)
    ) / B

    dW4 = A3.T @ dZ4

    db4 = np.sum(
        dZ4,
        axis=0,
        keepdims=True
    )

    dA3 = dZ4 @ W4.T

    dZ3 = (
        dA3 *
        relu_derivative(Z3)
    )

    dW3 = A2.T @ dZ3

    db3 = np.sum(
        dZ3,
        axis=0,
        keepdims=True
    )

    dA2 = dZ3 @ W3.T

    dZ2 = (
        dA2 *
        relu_derivative(Z2)
    )

    dW2 = A1.T @ dZ2

    db2 = np.sum(
        dZ2,
        axis=0,
        keepdims=True
    )

    dA1 = dZ2 @ W2.T

    dZ1 = (
        dA1 *
        relu_derivative(Z1)
    )

    dW1 = X.T @ dZ1

    db1 = np.sum(
        dZ1,
        axis=0,
        keepdims=True
    )

    gradients = {

        "dW1": dW1,
        "db1": db1,

        "dW2": dW2,
        "db2": db2,

        "dW3": dW3,
        "db3": db3,

        "dW4": dW4,
        "db4": db4
    }

    return gradients

def update_parameters(
    parameters,
    gradients,
    learning_rate
):

    for l in range(1, 5):

        parameters[f"W{l}"] -= (
            learning_rate *
            gradients[f"dW{l}"]
        )

        parameters[f"b{l}"] -= (
            learning_rate *
            gradients[f"db{l}"]
        )

    return parameters

def predict(X, parameters):

    Y_hat, _ = forward_propagation(
        X,
        parameters
    )

    predictions = np.argmax(
        Y_hat,
        axis=1
    )

    return predictions, Y_hat

learning_rate = 0.01

batch_size = 128

epochs = 100

patience = 15

print("\nTraining settings:")
print("Learning rate:", learning_rate)
print("Batch size:", batch_size)
print("Maximum epochs:", epochs)
print("Early stopping patience:", patience)

train_losses = []
val_losses = []

train_accuracies = []
val_accuracies = []

best_val_loss = np.inf

best_parameters = None

patience_counter = 0


for epoch in range(epochs):
    permutation = np.random.permutation(
        len(X_train)
    )

    X_train_shuffled = X_train[permutation]

    Y_train_shuffled = Y_train[permutation]

    num_batches = int(
        np.ceil(
            len(X_train) / batch_size
        )
    )

    for batch in range(num_batches):

        start = batch * batch_size

        end = min(
            start + batch_size,
            len(X_train)
        )

        X_batch = X_train_shuffled[start:end]

        Y_batch = Y_train_shuffled[start:end]

        # Forward propagation
        Y_hat_batch, cache = forward_propagation(
            X_batch,
            parameters
        )

        # Backpropagation
        gradients = backward_propagation(
            Y_batch,
            Y_hat_batch,
            cache,
            parameters,
            class_weight_array
        )

        # Update weights
        parameters = update_parameters(
            parameters,
            gradients,
            learning_rate
        )

    train_predictions, train_probabilities = predict(
        X_train,
        parameters
    )

    train_loss = compute_loss(
        Y_train,
        train_probabilities,
        class_weight_array
    )

    val_predictions, val_probabilities = predict(
        X_val,
        parameters
    )

    val_loss = compute_loss(
        Y_val,
        val_probabilities,
        class_weight_array
    )

    # Save history
    train_losses.append(train_loss)
    val_losses.append(val_loss)

    print(
        f"Epoch {epoch + 1:03d}/{epochs} | "
        f"Train Loss: {train_loss:.4f} | "
        f"Val Loss: {val_loss:.4f} | "
    )

    if val_loss < best_val_loss:

        best_val_loss = val_loss

        # Save best parameters
        best_parameters = {
            key: value.copy()
            for key, value in parameters.items()
        }

        patience_counter = 0

    else:

        patience_counter += 1

    if patience_counter >= patience:

        print(
            f"\nEarly stopping at epoch "
            f"{epoch + 1}"
        )

        break

parameters = best_parameters

print("\nBest validation loss:",
      best_val_loss)

test_predictions, test_probabilities = predict(
    X_test,
    parameters
)

print("\nTest predictions generated.")

plt.figure(figsize=(8, 5))

plt.plot(
    train_losses,
    label="Training Loss"
)

plt.plot(
    val_losses,
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.title(
    "Training and Validation Loss"
)

plt.legend()

plt.grid(True)

plt.show()

true_counts = np.bincount(
    y_test,
    minlength=K
)

predicted_counts = np.bincount(
    test_predictions,
    minlength=K
)

x = np.arange(K)

width = 0.35

plt.figure(figsize=(9, 5))

plt.bar(
    x - width / 2,
    true_counts,
    width,
    label="True"
)

plt.bar(
    x + width / 2,
    predicted_counts,
    width,
    label="Predicted"
)

plt.xlabel("Forest Cover Type")
plt.ylabel("Number of Samples")

plt.title(
    "True vs Predicted Class Distribution"
)

plt.xticks(
    x,
    range(1, 8)
)

plt.legend()

plt.show()

sample_probabilities = test_probabilities[:10]

sample_predictions = test_predictions[:10]

print("\nFirst 10 Predictions:")
print(
    sample_predictions
)

print("\nProbability Distribution:")
print(
    sample_probabilities
)

print("\nSum of probabilities for first sample:")

print(
    np.sum(sample_probabilities[0])
)